apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    app: {{ .Values.backend.service.selector.appName }}
  ports:
    - protocol: {{ .Values.backend.service.protocol }}
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      nodePort: {{ .Values.backend.service.nodePort }}
  type: NodePort