apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqldb.service.name }}
spec:
  selector:
    app: {{ .Values.mysqldb.service.selector.appName }}
  ports:
    - protocol: {{ .Values.mysqldb.service.protocol }}
      port: {{ .Values.mysqldb.service.port }}