frontend:
  replicaCount: 1
  selector:
    label:
      appName: frontend
  template:
    label: 
      appName: frontend
  containerName: frontend
  image:
    repository: yashchouhan/frontend
    tag: 14
  containerPort: 80

  service:
    name: frontend
    selector:
      appName: frontend
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000

backend:
  replicaCount: 1
  selector:
    label:
      appName: backend
  template:
    label: 
      appName: backend
  containerName: backend
  image:
    repository: yashchouhan/backend
    tag: 14
  containerPort: 8080
  configMapName: spring-config

  service:
    name: backend
    selector:
      appName: backend
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000

mysqldb:
  serviceName: mysqldb
  replicaCount: 1
  selector:
    label:
      appName: mysqldb
  template:
    label: 
      appName: mysqldb
  containerName: mysqldb
  image:
    repository: mysql
    tag: 5.7
  containerPort: 3306
  configMapName: mysqldb-config
  volumeMounts:
    name: mysql-data
    mountPath: /var/lib/mysql
  volumes:
    name: mysql-data
    path: /opt/db
  rootPassword: yash
  dbName: test
    
  service:
    name: mysqldb
    selector:
      appName: mysqldb
    protocol: TCP
    port: 3306
